### ISSUE TITLE
最近几天PHP脚本用定时任务自动执行总是失败

### ISSUE THREAD

**Issue by tyhunter** [iddddg/hostloc#1]
Log如下：
登录成功（*****）
初始信息（用户组:中级会员,金钱:233,威望:16,积分:239）
刷分中 ++++++++++++++++++++++++++++++ 完成
结束信息（用户组:中级会员,金钱:253,威望:16,积分:259）
2019-06-21 06:00:16
----------------------------------------------------------
----------------------------------------------------------
登录失败（*****）
2019-06-22 06:00:03
----------------------------------------------------------
----------------------------------------------------------
登录失败（*****）
2019-06-23 06:00:03
----------------------------------------------------------
----------------------------------------------------------
登录失败（*****）
2019-06-24 06:00:03
----------------------------------------------------------

用html网页手动刷分是正常的

**Comment by iddddg** [comment]
我这一天两条定时任务,早6点,晚6点,每天都失败其中一次,相当于签到正常,所以一直懒得查原因,你可以暂时先这样,回头我查查

**Comment by tyhunter** [comment]
@iddddg 哈哈哈，不过习惯了日常上loc划水，签到失败了就手动执行服务器上的html刷分了，估计最近论坛添加验证之类的了（或者服务器IP被盯上了？），还是感谢大佬开发了这个好东西

**Comment by iddddg** [comment]
论坛偶尔防CC吧,所以误伤估计,可以每条两条,稳一点的

**Comment by fx-k** [comment]
哈哈我也是这个问题，不知道是不是服务器ip被禁了，一直登录失败，手动执行脚本也是一样。要不增加一下时间间隔呗，防cc

**Comment by iddddg** [comment]
@tyhunter @keke1229488344 已经增加了随机延迟，并且每日多次尝试，所以请把定时任务设置为每小时访问一次php脚本，晚上9点会推送当天签到失败的账号信息，但其实任然会继续每小时尝试签到。暂时就这样吧，我准备来看登录失败的原因时候，本机就一直正常登陆。over
