### ISSUE TITLE
20240927今天各种登陆失败~大佬快看看

### ISSUE THREAD

**Issue by xuanvivo** [iddddg/hostloc#11]
<img width="119" alt="image" src="https://github.com/user-attachments/assets/ff39a2e6-dda1-4cfc-879b-ded69e9526cc">

**Comment by iddddg** [comment]
收到，应该是论坛开了防CC，回头研究看看

**Comment by michaeltan1120** [comment]
一样的问题

**Comment by iddddg** [comment]
@xuanvivo @michaeltan1120 b75bbf9cbaa0e01974d49295a4b762426ac8eea4 更新了，加了CC防护的Cookie参数。
大概原理就是先访问页面获得相关参数，然后AES解密放到Cookie里，我本地和Github Actions测试都是OK的，你们更新代码试下呢，结果帮忙反馈下，3Q。

**Comment by xuanvivo** [comment]
> @xuanvivo @michaeltan1120 [b75bbf9](https://github.com/iddddg/hostloc/commit/b75bbf9cbaa0e01974d49295a4b762426ac8eea4) 更新了，加了CC防护的Cookie参数。 大概原理就是先访问页面获得相关参数，然后AES解密放到Cookie里，我本地和Github Actions测试都是OK的，你们更新代码试下呢，结果帮忙反馈下，3Q。

测试正常了，您辛苦。

**Comment by iddddg** [comment]
> > @xuanvivo @michaeltan1120 [b75bbf9](https://github.com/iddddg/hostloc/commit/b75bbf9cbaa0e01974d49295a4b762426ac8eea4) 更新了，加了CC防护的Cookie参数。 大概原理就是先访问页面获得相关参数，然后AES解密放到Cookie里，我本地和Github Actions测试都是OK的，你们更新代码试下呢，结果帮忙反馈下，3Q。
> 
> 测试正常了，您辛苦。

小问题客气
