### ISSUE TITLE
tgbot不能获取key

### ISSUE THREAD

**Issue by lukemin** [iddddg/hostloc#2]
如题。

**Comment by iddddg** [comment]
what？

**Comment by lukemin** [comment]
![3dc88dca391d7536c44ea2e9e4dce52](https://user-images.githubusercontent.com/12003375/64404190-b66c9600-d0ad-11e9-859c-3d0b7b398e50.jpg)

**Comment by iddddg** [comment]
拿之前的域名做了机场导致无法响应，已修复，谢谢反馈
