### ISSUE TITLE
使用正确的密码也会提示登录失败

### ISSUE THREAD

**Issue by 955s** [iddddg/hostloc#3]
登录失败（xxxx）
2019-09-19 11:19:04
![QQ图片20190919112635](https://user-images.githubusercontent.com/14900130/65211189-67245d80-dad0-11e9-867b-0a114d4e88fb.png)

**Comment by iddddg** [comment]
有删除目录下的account.dat文件吗，或者www用户运行php的话，可能在/homw/www/文件夹下的account.dat文件

**Comment by 955s** [comment]
还是不行，授予了www权限，也从新删除dat文件
这是account.dat下的内容
[{"username":"xxxx","password":"xxxxxxxxxxxx","status":"err","date":"2019-09-19"}]

**Comment by iddddg** [comment]
方便留个联系方式吗

**Comment by 955s** [comment]
xx

**Comment by iddddg** [comment]
因为论坛防D，防C，每天会在某些时间段登陆失败，所以设置定时任务每一小时执行一次，每晚9点，查看日志就行
