### ISSUE TITLE
php是每次只刷1次访问吗？

### ISSUE THREAD

**Issue by praming** [iddddg/hostloc#5]
看到文档说php每小时执行一次，每次是只刷一次访问么？
另外html好像没有存用户名密码，应该是适合本地手动操作的吧，如果在服务器定时访问url应该是不起作用吧？

**Comment by iddddg** [comment]
PHP版本,每次会访问大概30个,也就是其实一次就能刷完分了.但是有时候论坛会开启防C之类的导致失败.所以建议每小时执行一次,晚上9点会自动统计一下,只要成功一次就不通知,全失败就会推送通知
HTML版本,只能用浏览器访问,而且前提是你自己hostloc已经登陆了

**Comment by praming** [comment]
> PHP版本,每次会访问大概30个,也就是其实一次就能刷完分了.但是有时候论坛会开启防C之类的导致失败.所以建议每小时执行一次,晚上9点会自动统计一下,只要成功一次就不通知,全失败就会推送通知
> HTML版本,只能用浏览器访问,而且前提是你自己hostloc已经登陆了

好的，非常感谢。

**Comment by iddddg** [comment]
mjj
